### ISSUE TITLE
Inserir um id no label através do setAttribute

### ISSUE THREAD

**Issue by thiagopiacentini** [victordnt/victordnt.github.io#3]
Pensando no usuário, poderia inserir na `<label id="">` com o setAttribute, assim quando o usuário tocar no nome do role, pode marcar/desmarcar o checkbox.

https://github.com/victordnt/victordnt.github.io/blob/ead3e233d4ecd8263e565a4cfe893b5b56fce01a/igti/desafio1/js/main.js#L28

**Comment by victordnt** [comment]
É verdade! eu acabei confundindo qual dos dois faziam o label referenciar o input, acabei que nem vi que devia ter feito o setAttribute no id. Valeu por lembrar!

**Comment by victordnt** [comment]
corrigido nos commits [ce3c1fd](https://github.com/victordnt/victordnt.github.io/commit/ce3c1fd0b8cb08c37a766fbd9852a828b8eed23b) e [5c92207](https://github.com/victordnt/victordnt.github.io/commit/5c92207ac5f2710b91e5004c7e41abb8ec3b2c8f):)
